site_name: Analytico Wiki
site_url: https://vladcostin4.github.io/analytico/

theme:
  name: material
  palette:
    primary: indigo
    accent: blue
  features:
    - toc.integrate

nav:
  - Home: index.md
  - M1 - Project Foundation: m1.md
  - M2 - Technical Implementation: m2.md
  - M3 - Mockup and Landing Page: m3.md
  - M4 - User persona and user stories: m4.md

extra_css:
  - style.css
  
